function Footer(){
     document.write('<!--Start Back To Top Button--> <a href="javaScript:;" class="back-to-top"><i class="bx bxs-up-arrow-alt"></i></a>');
     document.write('<!--End Back To Top Button-->');
 document.write('<footer id="colophon" class="site-footer">');
 document.write('<section class="py-4 bg-dark-1">');
 document.write('<div class="container">');
 document.write(' <div class="row row-cols-1 row-cols-lg-2 row-cols-xl-4">');
 document.write('<div id="block-11" class="col widget widget_block widget_recent_comments"><div class="footer-section1 mb-3"><ol class="has-avatars has-dates has-excerpts wp-block-latest-comments"><li class="wp-block-latest-comments__comment"><img alt="" src="avatar.png" class="avatar avatar-48 photo wp-block-latest-comments__comment-avatar" height="48" width="48" loading="lazy"/><article><footer class="wp-block-latest-comments__comment-meta"><a class="wp-block-latest-comments__comment-author" href="">Kolyan</a> к <a class="wp-block-latest-comments__comment-link" href="">');
 document.write('Привет мир!</a><time datetime="2021-09-17T12:49:53+03:00" class="wp-block-latest-comments__comment-date">17.09.2021</time></footer><div class="wp-block-latest-comments__comment-excerpt"><p>Еще один комментарий</p>');
 document.write('</div></article></li><li class="wp-block-latest-comments__comment"><img alt="" src="avatar.png" class="avatar avatar-48 photo wp-block-latest-comments__comment-avatar" height="48" width="48" loading="lazy"/><article><footer class="wp-block-latest-comments__comment-meta"><a class="wp-block-latest-comments__comment-author" href="">Kolyan</a> к <a class="wp-block-latest-comments__comment-link" href="">Привет мир!</a><time datetime="2021-09-17T12:45:29+03:00" class="wp-block-latest-comments__comment-date">17.09.2021</time></footer><div class="wp-block-latest-comments__comment-excerpt"><p>Оставляю комментарий</p>');
 document.write('</div></article></li></ol></div></div><div id="block-12" class="col widget widget_block widget_tag_cloud"><div class="footer-section1 mb-3"><p class="wp-block-tag-cloud"><a href="category-bleach.html" class="tag-cloud-link tag-link-19 tag-link-position-1" style="font-size: 22pt;" aria-label="Блич (4 элемента)">Блич</a>');
 document.write('<a href="single-2.html" class="tag-cloud-link tag-link-20 tag-link-position-2" style="font-size: 8pt;" aria-label="Ичиго (1 элемент)">Ичиго</a>');
 document.write('<a href="single-3.html" class="tag-cloud-link tag-link-17 tag-link-position-3" style="font-size: 22pt;" aria-label="Рукиа (4 элемента)">Рукиа</a></p></div></div><div id="block-13" class="col widget widget_block widget_calendar"><div class="footer-section1 mb-3"><div class="aligncenter wp-block-calendar"><table id="wp-calendar" class="wp-calendar-table">');
  document.write('<caption>Сентябрь 2021</caption>');
  document.write('<thead>');
  document.write('<tr>');
    document.write('<th scope="col" title="Понедельник">Пн</th>');
    document.write('<th scope="col" title="Вторник">Вт</th>');
    document.write('<th scope="col" title="Среда">Ср</th>');
    document.write('<th scope="col" title="Четверг">Чт</th>');
    document.write('<th scope="col" title="Пятница">Пт</th>');
    document.write('<th scope="col" title="Суббота">Сб</th>');
    document.write('<th scope="col" title="Воскресенье">Вс</th>');
   document.write('</tr>');
   document.write('</thead>');
   document.write('<tbody>');
   document.write('<tr>');
    document.write('<td colspan="2" class="pad">&nbsp;</td><td>1</td><td>2</td><td>3</td><td>4</td><td>5</td>');
  document.write('</tr>');
  document.write('<tr>');
    document.write('<td>6</td><td>7</td><td>8</td><td>9</td><td>10</td><td>11</td><td>12</td>');
  document.write('</tr>');
  document.write('<tr>');
    document.write('<td>13</td><td>14</td><td>15</td><td>16</td><td><a href="" aria-label="Записи, опубликованные 17.09.2021">17</a></td><td>18</td><td id="today">19</td>');
  document.write('</tr>');
  document.write('<tr>');
    document.write('<td>20</td><td>21</td><td>22</td><td>23</td><td>24</td><td>25</td><td>26</td>');
  document.write('</tr>');
  document.write('<tr>');
    document.write('<td>27</td><td>28</td><td>29</td><td>30</td>');
    document.write('<td class="pad" colspan="3">&nbsp;</td>');
  document.write('</tr>');
  document.write('</tbody>');
  document.write('</table><nav aria-label="Предыдущий и следующий месяцы" class="wp-calendar-nav">');
     document.write('<span class="wp-calendar-nav-prev">&nbsp;</span>');
     document.write('<span class="pad">&nbsp;</span>');
    document.write('<span class="wp-calendar-nav-next">&nbsp;</span>');
   document.write('</nav></div></div></div><div id="block-14" class="col widget widget_block"><div class="footer-section1 mb-3"><ul class="wp-block-page-list"><li class="wp-block-pages-list__item"><a class="wp-block-pages-list__item__link" href="page.html">Выпадающее меню</a></li><li class="wp-block-pages-list__item"><a class="wp-block-pages-list__item__link" href="page-2.html">Контакты</a></li><li class="wp-block-pages-list__item"><a class="wp-block-pages-list__item__link" href="page-3.html">О нас</a></li><li class="wp-block-pages-list__item"><a class="wp-block-pages-list__item__link" href="page-4.html">Музыка</a></li><li class="wp-block-pages-list__item"><a class="wp-block-pages-list__item__link" href="page-5.html">Герои</a></li><li class="wp-block-pages-list__item"><a class="wp-block-pages-list__item__link" href="page-6.html">Пример страницы</a></li></ul></div></div>           </div>');
           document.write('<hr>');
           document.write('<div class="row row-cols-1 row-cols-md-2 align-items-center">');
             document.write('<div class="col">');
               document.write('<p class="mb-0">');
       document.write('<div class="site-info">');
       document.write('<a href="https://wordpress.org/">');
         document.write('Сайт работает на WordPress      </a>');
       document.write('<span class="sep"> | </span>');
         document.write('тема: bleach | автор: <a href="http://GetUnitXNikolay@yandex.ru">Nikolay Web</a>.   </div><!-- .site-info -->');
               document.write('</p>');
             document.write('</div>');
             document.write('<div class="col text-end">');
             document.write('</div>');
          document.write(' </div>');
          document.write(' <!--end row-->');
        document.write(' </div>');
      document.write(' </section>');
   document.write('</footer><!-- #colophon -->');
 document.write('</div><!-- #page -->');
 document.write('<div class="switcher-wrapper">');
     document.write('<div class="switcher-btn"> <i class="bx bx-cog bx-spin"></i>');
     document.write('</div>');
     document.write('<div class="switcher-body">');
       document.write('<div class="d-flex align-items-center">');
        document.write(' <h5 class="mb-0 text-uppercase">Настройки Темы</h5>');
         document.write('<button type="button" class="btn-close ms-auto close-switcher" aria-label="Close"></button>');
       document.write('</div>');
       document.write('<hr>');
       document.write('<p class="mb-0">Цветовая текстура</p>');
       document.write('<hr>');
       document.write('<ul class="switcher">');
         document.write('<li id="theme1"></li>');
         document.write('<li id="theme2"></li>');
         document.write('<li id="theme3"></li>');
         document.write('<li id="theme4"></li>');
         document.write('<li id="theme5"></li>');
         document.write('<li id="theme6"></li>');
       document.write('</ul>');
       document.write('<hr>');
       document.write('<p class="mb-0">Градиентный фон</p>');
       document.write('<hr>');
       document.write('<ul class="switcher">');
         document.write('<li id="theme7"></li>');
         document.write('<li id="theme8"></li>');
         document.write('<li id="theme9"></li>');
         document.write('<li id="theme10"></li>');
         document.write('<li id="theme11"></li>');
         document.write('<li id="theme12"></li>');
         document.write('<li id="theme13"></li>');
         document.write('<li id="theme14"></li>');
         document.write('<li id="theme15"></li>');
       document.write('</ul>');
     document.write('</div>');
   document.write('</div>');
 document.write("<script src='wp-content/themes/bleach/assets/js/pace.min.js?ver=1' id='bleach-pace-js-js'></script>");
document.write("<script src='wp-content/themes/bleach/assets/js/bootstrap.bundle.min.js?ver=1' id='bleach-bundle-js-js'></script>");
document.write("<script src='wp-content/themes/bleach/assets/plugins/simplebar/js/simplebar.min.js?ver=1' id='bleach-simplebar-js-js'></script>");
document.write("<script src='wp-content/themes/bleach/assets/plugins/OwlCarousel/js/owl.carousel.min.js?ver=1' id='bleach-carousel-js-js'></script>");
document.write("<script src='wp-content/themes/bleach/assets/plugins/OwlCarousel/js/owl.carousel2.thumbs.min.js?ver=1' id='bleach-carousel2-js-js'></script>");
document.write("<script src='wp-content/themes/bleach/assets/plugins/metismenu/js/metisMenu.min.js?ver=1' id='bleach-metisMenu-js-js'></script>");
document.write("<script src='wp-content/themes/bleach/assets/plugins/perfect-scrollbar/js/perfect-scrollbar.js?ver=1' id='bleach-perfect-js-js'></script>");
document.write("<script src='wp-content/themes/bleach/assets/js/app.js?ver=1' id='bleach-apps-js-js'></script>");
document.write("<script src='wp-content/themes/bleach/assets/js/index.js?ver=1' id='bleach-index-js-js'></script>");
document.write("<script src='wp-includes/js/wp-embed.min.js?ver=5.8.1' id='wp-embed-js'></script>");
}