<?php
/**
 * Hooks for importer
 *
 * @package ProgriSaaS
 */


/**
 * Importer the demo content
 *
 * @since  1.0
 *
 */
function progrisaas_importer() {
	return array(
		array(
			'name'       => 'Home 1 - Startup Agency',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home1.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home1/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 1',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 2 - App Landing',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home2.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home2/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 2',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 3 - Digital Agency',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home3.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home3/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 3',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 4 - SaaS Landing',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home4.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home4/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 4',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 5 - Mobile App',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home5.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home5/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 5',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 6 - Design Agency',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home6.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home6/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 6',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 7 - Event & Conference',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home7.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home7/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 7',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 8 - HR Managment',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home8.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home8/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 8',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 9 - Software',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home9.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home9/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 9',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 10 - Project Managment',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home10.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home10/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 10',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 11 - Digital Marketing',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home11.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home11/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 11',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 12 - Analytics Software',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home12.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home12/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 12',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 13 - Product Landing',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home13.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home13/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 13',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 14 - Security Software',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home14.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home14/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 14',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 15 - Support Chat Platform',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home15.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home15/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 15',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 16 - Crypto App',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home16.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home16/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 16',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 17 - Payment Process',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home17.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home17/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 17',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 18 - Web hosting',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home18.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home18/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 18',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 19 - Email Client',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home19.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home19/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 19',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 20 - Tech Home',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home20.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home20/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 20',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 21 - Food Delivery',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home21.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home21/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 21',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 22 - Fitness Home',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home22.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home22/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 22',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 23 - Webinar Home',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home23.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home23/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 23',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 24 - Split Slider Showcase',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home24.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home24/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 24',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
		array(
			'name'       => 'Home 25 - Product Slider',
			'preview'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home25.jpg',
			'content'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/home25/demo-content.xml',
			'customizer' => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/customizer.dat',
			'widgets'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/widgets.wie',
			'sliders'    => 'https://progrisaas.s3-ap-southeast-1.amazonaws.com/demo-content/sliders.zip',
			'pages'      => array(
				'front_page' => 'Home 25',
				'blog'       => 'Blog',
				'shop'       => 'Shop',
				'cart'       => 'Cart',
				'checkout'   => 'Checkout',
				'my_account' => 'My Account',
			),
		),
	);
}

add_filter( 'soo_demo_packages', 'progrisaas_importer', 30 );